App({
    onLaunch: function () {
      console.log('App Launch')
    },
    onShow: function () {
      console.log('App Show')
    },
    onHide: function () {
      console.log('App Hide')
    },
    globalData:{
      userInfo:{},
      schedule:{
        "614":[{
            "home":"俄罗斯",
            "away":"沙特阿拉伯",
            "time":"23:00",
            "home_flag":"/image/flags/Russia.svg",
            "away_flag":"/image/flags/Saudi.svg",
            "note":"A组"
        }],
        "615":[{
            "home":"埃及",
            "away":"乌拉圭",
            "time":"20:00",
            "home_flag":"/image/flags/Egypt.svg",
            "away_flag":"/image/flags/Uruguay.svg",
            "note":"A组"
        },{
            "home":"摩洛哥",
            "away":"伊朗",
            "time":"23:00",
            "home_flag":"/image/flags/Morocco.svg",
            "away_flag":"/image/flags/Iran.svg",
            "note":"B组"
        }],
        "616":[{
            "home":"葡萄牙",
            "away":"西班牙",
            "time":"2:00",
            "home_flag":"/image/flags/Portugal.svg",
            "away_flag":"/image/flags/Spain.svg",
            "note":"B组"
        },{
            "home":"法国",
            "away":"澳大利亚",
            "time":"18:00",
            "home_flag":"/image/flags/France.svg",
            "away_flag":"/image/flags/Australia.svg",
            "note":"C组"
        },{
            "home":"阿根廷",
            "away":"冰岛",
            "time":"21:00",
            "home_flag":"/image/flags/Argentina.svg",
            "away_flag":"/image/flags/Iceland.svg",
            "note":"D组"
        }],
        "617":[{
            "home":"秘鲁",
            "away":"丹麦",
            "time":"0:00",
            "home_flag":"/image/flags/Peru.svg",
            "away_flag":"/image/flags/Denmark.svg",
            "note":"C组"
        },{
            "home":"克罗地亚",
            "away":"尼日利亚",
            "time":"3:00",
            "home_flag":"/image/flags/Croatia.svg",
            "away_flag":"/image/flags/Nigeria.svg",
            "note":"D组"
        },{
            "home":"哥斯达黎加",
            "away":"塞尔维亚",
            "time":"20:00",
            "home_flag":"/image/flags/Costa.svg",
            "away_flag":"/image/flags/Serbia.svg",
            "note":"E组"
        },{
            "home":"德国",
            "away":"墨西哥",
            "time":"23:00",
            "home_flag":"/image/flags/Germany.svg",
            "away_flag":"/image/flags/Mexico.svg",
            "note":"F组"
        }],
        "618":[{
            "home":"巴西",
            "away":"瑞士",
            "time":"2:00",
            "home_flag":"/image/flags/Brazil.svg",
            "away_flag":"/image/flags/Switzerland.svg",
            "note":"E组"
        },{
            "home":"瑞典",
            "away":"韩国",
            "time":"20:00",
            "home_flag":"/image/flags/Sweden.svg",
            "away_flag":"/image/flags/Korea.svg",
            "note":"F组"
        },{
            "home":"比利时",
            "away":"巴拿马",
            "time":"23:00",
            "home_flag":"/image/flags/Belgium.svg",
            "away_flag":"/image/flags/Panama.svg",
            "note":"G组"
        }],
        "619":[{
            "home":"突尼斯",
            "away":"英格兰",
            "time":"2:00",
            "home_flag":"/image/flags/Tunisia.svg",
            "away_flag":"/image/flags/England.svg",
            "note":"G组"
        },{
            "home":"哥伦比亚",
            "away":"日本",
            "time":"20:00",
            "home_flag":"/image/flags/Colombia.svg",
            "away_flag":"/image/flags/Japan.svg",
            "note":"H组"
        },{
            "home":"波兰",
            "away":"塞内加尔",
            "time":"23:00",
            "home_flag":"/image/flags/Poland.svg",
            "away_flag":"/image/flags/Senegal.svg",
            "note":"H组"
        }],
        "620":[{
            "home":"俄罗斯",
            "away":"埃及",
            "time":"2:00",
            "home_flag":"/image/flags/Russia.svg",
            "away_flag":"/image/flags/Egypt.svg",
            "note":"A组"
        },{
            "home":"葡萄牙",
            "away":"摩洛哥",
            "time":"20:00",
            "home_flag":"/image/flags/Portugal.svg",
            "away_flag":"/image/flags/Morocco.svg",
            "note":"B组"
        },{
            "home":"乌拉圭",
            "away":"沙特阿拉伯",
            "time":"23:00",
            "home_flag":"/image/flags/Morocco.svg",
            "away_flag":"/image/flags/Saudi.svg",
            "note":"A组"
        }],
        "621":[{
            "home":"伊朗",
            "away":"西班牙",
            "time":"2:00",
            "home_flag":"/image/flags/Iran.svg",
            "away_flag":"/image/flags/Spain.svg",
            "note":"B组"
        },{
            "home":"丹麦",
            "away":"澳大利亚",
            "time":"20:00",
            "home_flag":"/image/flags/Denmark.svg",
            "away_flag":"/image/flags/Australia.svg",
            "note":"C组"
        },{
            "home":"法国",
            "away":"秘鲁",
            "time":"23:00",
            "home_flag":"/image/flags/France.svg",
            "away_flag":"/image/flags/Peru.svg",
            "note":"C组"
        }],
        "622":[{
            "home":"阿根廷",
            "away":"克罗地亚",
            "time":"2:00",
            "home_flag":"/image/flags/Argentina.svg",
            "away_flag":"/image/flags/Croatia.svg",
            "note":"D组"
        },{
            "home":"巴西",
            "away":"哥斯达黎加",
            "time":"20:00",
            "home_flag":"/image/flags/Brazil.svg",
            "away_flag":"/image/flags/Costa.svg",
            "note":"E组"
        },{
            "home":"尼日利亚",
            "away":"冰岛",
            "time":"23:00",
            "home_flag":"/image/flags/Nigeria.svg",
            "away_flag":"/image/flags/Iceland.svg",
            "note":"D组"
        }],
        "623":[{
            "home":"塞尔维亚",
            "away":"瑞士",
            "time":"2:00",
            "home_flag":"/image/flags/Serbia.svg",
            "away_flag":"/image/flags/Switzerland.svg",
            "note":"E组"
        },{
            "home":"比利时",
            "away":"突尼斯",
            "time":"20:00",
            "home_flag":"/image/flags/Belgium.svg",
            "away_flag":"/image/flags/Tunisia.svg",
            "note":"G组"
        },{
            "home":"韩国",
            "away":"墨西哥",
            "time":"23:00",
            "home_flag":"/image/flags/Korea.svg",
            "away_flag":"/image/flags/Mexico.svg",
            "note":"F组"
        }],
        "624":[{
            "home":"德国",
            "away":"瑞典",
            "time":"2:00",
            "home_flag":"/image/flags/Germany.svg",
            "away_flag":"/image/flags/Sweden.svg",
            "note":"F组"
        },{
            "home":"英格兰",
            "away":"巴拿马",
            "time":"20:00",
            "home_flag":"/image/flags/England.svg",
            "away_flag":"/image/flags/Panama.svg",
            "note":"G组"
        },{
            "home":"日本",
            "away":"塞内加尔",
            "time":"23:00",
            "home_flag":"/image/flags/Japan.svg",
            "away_flag":"/image/flags/Senegal.svg",
            "note":"H组"
        }],
        "625":[{
            "home":"波兰",
            "away":"哥伦比亚",
            "time":"2:00",
            "home_flag":"/image/flags/Poland.svg",
            "away_flag":"/image/flags/Colombia.svg",
            "note":"H组"
        },{
            "home":"沙特阿拉伯",
            "away":"埃及",
            "time":"22:00",
            "home_flag":"/image/flags/Saudi.svg",
            "away_flag":"/image/flags/Egypt.svg",
            "note":"A组"
        },{
            "home":"乌拉圭",
            "away":"俄罗斯",
            "time":"22:00",
            "home_flag":"/image/flags/Uruguay.svg",
            "away_flag":"/image/flags/Russia.svg",
            "note":"A组"
        }],
        "626":[{
            "home":"西班牙",
            "away":"摩洛哥",
            "time":"2:00",
            "home_flag":"/image/flags/Spain.svg",
            "away_flag":"/image/flags/Morocco.svg",
            "note":"B组"
        },{
            "home":"伊朗",
            "away":"葡萄牙",
            "time":"2:00",
            "home_flag":"/image/flags/Iran.svg",
            "away_flag":"/image/flags/Portugal.svg",
            "note":"B组"
        },{
            "home":"澳大利亚",
            "away":"秘鲁",
            "time":"22:00",
            "home_flag":"/image/flags/Australia.svg",
            "away_flag":"/image/flags/Peru.svg",
            "note":"C组"
        },{
            "home":"丹麦",
            "away":"法国",
            "time":"22:00",
            "home_flag":"/image/flags/Denmark.svg",
            "away_flag":"/image/flags/France.svg",
            "note":"C组"
        }],
        "627":[{
            "home":"冰岛",
            "away":"克罗地亚",
            "time":"2:00",
            "home_flag":"/image/flags/Iceland.svg",
            "away_flag":"/image/flags/Croatia.svg",
            "note":"D组"
        },{
            "home":"尼日利亚",
            "away":"阿根廷",
            "time":"2:00",
            "home_flag":"/image/flags/Nigeria.svg",
            "away_flag":"/image/flags/Argentina.svg",
            "note":"D组"
        },{
            "home":"韩国",
            "away":"德国",
            "time":"22:00",
            "home_flag":"/image/flags/Korea.svg",
            "away_flag":"/image/flags/Germany.svg",
            "note":"F组"
        },{
            "home":"墨西哥",
            "away":"瑞典",
            "time":"22:00",
            "home_flag":"/image/flags/Mexico.svg",
            "away_flag":"/image/flags/Sweden.svg",
            "note":"F组"
        }],
        "628":[{
            "home":"瑞士",
            "away":"哥斯达黎加",
            "time":"2:00",
            "home_flag":"/image/flags/Switzerland.svg",
            "away_flag":"/image/flags/Costa.svg",
            "note":"E组"
        },{
            "home":"塞尔维亚",
            "away":"巴西",
            "time":"2:00",
            "home_flag":"/image/flags/Serbia.svg",
            "away_flag":"/image/flags/Brazil.svg",
            "note":"E组"
        },{
            "home":"日本",
            "away":"波兰",
            "time":"22:00",
            "home_flag":"/image/flags/Japan.svg",
            "away_flag":"/image/flags/Poland.svg",
            "note":"H组"
        },{
            "home":"塞内加尔",
            "away":"哥伦比亚",
            "time":"22:00",
            "home_flag":"/image/flags/Senegal.svg",
            "away_flag":"/image/flags/Colombia.svg",
            "note":"H组"
        }],
        "629":[{
            "home":"英格兰",
            "away":"比利时",
            "time":"2:00",
            "home_flag":"/image/flags/England.svg",
            "away_flag":"/image/flags/Belgium.svg",
            "note":"G组"
        },{
            "home":"巴拿马",
            "away":"突尼斯",
            "time":"2:00",
            "home_flag":"/image/flags/Panama.svg",
            "away_flag":"/image/flags/Tunisia.svg",
            "note":"G组"
        }],
        "630":[{
            "home":"未定",
            "away":"未定",
            "time":"22:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        }],
        "71":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        },{
            "home":"未定",
            "away":"未定",
            "time":"22:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        }],
        "72":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        },{
            "home":"未定",
            "away":"未定",
            "time":"22:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        }],
        "73":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        },{
            "home":"未定",
            "away":"未定",
            "time":"22:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        }],
        "74":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/8决赛"
        }],
        "76":[{
            "home":"未定",
            "away":"未定",
            "time":"22:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/4决赛"
        }],
        "77":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/4决赛"
        },{
            "home":"未定",
            "away":"未定",
            "time":"22:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/4决赛"
        }],
        "78":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"1/4决赛"
        }],
        "711":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"半决赛"
        }],
        "712":[{
            "home":"未定",
            "away":"未定",
            "time":"2:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"半决赛"
        }],
        "714":[{
            "home":"未定",
            "away":"未定",
            "time":"22:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"3/4决赛"
        }],
        "715":[{
            "home":"未定",
            "away":"未定",
            "time":"23:00",
            "home_flag":"/image/flags/undown.svg",
            "away_flag":"/image/flags/undown.svg",
            "note":"决赛"
        }],
    }  
    }
  })